
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgre
  password: postgre

development:
  <<: *default
  database: searchtag

test:
  #<<: *default
  database: searchtag

production:
  #<<: *default
  database: searchtag
